FROM node:22 AS builder

WORKDIR /app
COPY package.json .
RUN npm i -g vite@5.2.0
COPY .yarn ./.yarn
COPY .yarnrc.yml .
RUN yarn install
COPY . .

ENV VITE_CORPORATE_NAME="KMPlus Consulting"
ENV VITE_FIREBASE_API_KEY="AIzaSyDHb1QG3EEmbAKaPfingVS4r6Enkfeju4I"
ENV VITE_FIREBASE_AUTH_DOMAIN=smartkmsystem-2705f.firebaseapp.com
ENV VITE_FIREBASE_PROJECT_ID=smartkmsystem-2705f
ENV VITE_FIREBASE_STORAGE_BUCKET=smartkmsystem-2705f.appspot.com
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=634072245724
ENV VITE_FIREBASE_APP_ID=1:634072245724:web:bc597de032b02082f95b19
ENV VITE_JWT_KEY=smartkms2022
ENV VITE_API_KEY=smartkms20221

ENV VITE_API_EMPLOYEES_SERVICE_URL=https://employee-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_AUTH_SERVICE_URL=https://user-auth-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_CMS_SERVICE_URL=https://cms-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_SOCIAL_SERVICE_URL=https://social-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_SSO_SERVICE_URL=https://user-auth-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_NOTIFICATIONS_SERVICE_URL=https://notification-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_SMARTPLAN_SERVICE_URL=https://smartplan-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_COURSE_SERVICE_URL=https://course-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_SEARCH_ENGINE_SERVICE_URL=https://search-engine-qa-portaverse-staging.ilcs.co.id
ENV VITE_SSO_URL=https://sso-qa-portaverse-staging.ilcs.co.id
ENV VITE_KMS_URL=https://knowledge-qa-portaverse-staging.ilcs.co.id
ENV VITE_LMS_URL=https://learning-qa-portaverse-staging.ilcs.co.id
ENV VITE_TMS_URL=https://talent-qa-portaverse-staging.ilcs.co.id
ENV VITE_IMS_URL=https://ims-qa-portaverse-staging.ilcs.co.id
ENV VITE_CMS_URL=https://cms-frontend-qa-portaverse-staging.ilcs.co.id
ENV VITE_NAVBAR_URL=https://navbar-qa-portaverse-staging.ilcs.co.id/assets/remoteEntry.js
ENV VITE_API_SIGNATURE_SERVICE_URL=https://signature-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_DAILY_QUIZ_SERVICE_URL=https://daily-quiz-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_ASSESSMENT_SERVICE_URL=https://assessment-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_DEVELOPMENT_PLAN_SERVICE_URL=https://development-plan-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_INNOVATION_SERVICE_URL=https://innovation-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_KMAP_SERVICE_URL=https://kmap-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_REPOSITORY_SERVICE_URL=https://repository-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_EXTERNAL_USER_URL=https://user-external-qa-portaverse-staging.ilcs.co.id
ENV VITE_API_GAMIFICATION_SERVICE_URL=https://gamification-qa-portaverse-staging.ilcs.co.id


RUN yarn build

FROM nginx:stable-alpine AS server
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
