FROM node:16.16-alpine AS builder

#ARG VITE_CORPORATE_NAME
#ARG VITE_FIREBASE_API_KEY
#ARG VITE_FIREBASE_AUTH_DOMAIN
#ARG VITE_FIREBASE_DATABASE_URL
#ARG VITE_FIREBASE_PROJECT_ID
#ARG VITE_FIREBASE_STORAGE_BUCKET
#ARG VITE_FIREBASE_MESSAGING_SENDER_ID
#ARG VITE_FIREBASE_APP_ID
#ARG VITE_JWT_KEY
#ARG VITE_API_KEY
#ARG VITE_API_AUTH_SERVICE_URL
#ARG VITE_KMS_URL
#ARG VITE_LMS_URL
#ARG VITE_TMS_URL

WORKDIR /app
COPY package.json .
RUN npm i -g vite
COPY .yarn ./.yarn
COPY .yarnrc.yml .
RUN yarn install
COPY . .

ENV VITE_CORPORATE_NAME="KMPlus Consulting"
ENV VITE_FIREBASE_API_KEY="AIzaSyDHb1QG3EEmbAKaPfingVS4r6Enkfeju4I"
ENV VITE_FIREBASE_AUTH_DOMAIN=smartkmsystem-2705f.firebaseapp.com
ENV VITE_FIREBASE_PROJECT_ID=smartkmsystem-2705f
ENV VITE_FIREBASE_STORAGE_BUCKET=smartkmsystem-2705f.appspot.com
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=634072245724
ENV VITE_FIREBASE_APP_ID=1:634072245724:web:bc597de032b02082f95b19
ENV VITE_JWT_KEY=smartkms2022
ENV VITE_API_KEY=smartkms20221

ENV VITE_API_EMPLOYEES_SERVICE_URL=https://employee-service-portaverse.pelindo.co.id
ENV VITE_API_AUTH_SERVICE_URL=https://user-auth-service-portaverse.pelindo.co.id
ENV VITE_API_SSO_SERVICE_URL=https://user-auth-service-portaverse.pelindo.co.id
ENV VITE_KMS_URL=https://knowledge-portaverse.pelindo.co.id
ENV VITE_LMS_URL=https://learning.pelindo.co.id
ENV VITE_TMS_URL=https://talent.pelindo.co.id


#RUN VITE_CORPORATE_NAME=$VITE_CORPORATE_NAME \
#    VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
#    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
#    VITE_FIREBASE_DATABASE_URL=$VITE_FIREBASE_DATABASE_URL \
#    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
#    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
#    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
#    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
#    VITE_JWT_KEY=$VITE_JWT_KEY \
#    VITE_API_KEY=$VITE_API_KEY \
#    VITE_API_AUTH_SERVICE_URL=$VITE_API_AUTH_SERVICE_URL \
#    VITE_KMS_URL=$VITE_KMS_URL \
#    VITE_LMS_URL=$VITE_LMS_URL \
#    VITE_TMS_URL=$VITE_TMS_URL \
#    yarn build
RUN yarn build

FROM nginx:stable-alpine AS server
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
