const colors = require("tailwindcss/colors");

module.exports = {
  important: true,
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      yellow: colors.yellow,
      primary1: "#C9F3FB",
      primary4: "#93E2F7",
      primary3: "#016DB2",
      primary4: "#005499",
      primary5: "#003F80",
      primary6: "#4EAEEC",
      secondary1: "#1192E8",
      secondaryCyan: "#37B6E2",
      bg1: "#F2F4F6",
      bg2: "#F2F4F8",
      bg3: "#F6F6F6",
      bg4: "#FBFBFB",
      green: "#4BB543",
      green1: "#4BB543",
      grey: "#C1C7CD",
      grey2: "#C4C4C4",
      lightGrey: "#DDE1E6",
      darkGrey: "#878D96",
      gray: colors.gray,
      text1: "#444444",
      white: colors.white,
      red: colors.red,
      red1: "#CB0000",
      teal: colors.teal,
      black: colors.black,
      coffee: "#444444",
      baseGrey: "#325366",
      baseGradient: "#6CC7FE",
      topGradient: "#111111",
      iconGradient: "#FEFEFE",
    },
    fontFamily: {
      primary: ["Inter", "ui-serif", "Georgia"],
      secondary: ["Inter", "Roboto", "system-ui"],
    },
    plugins: [],
  },
};
